# Generated by Django 6.1.1 on 2026-09-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='DE', max_length=2)),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Steuernummer')),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='USt-IdNr.')),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_small_business', models.BooleanField(default=False, verbose_name='Kleinunternehmerregelung (§19 UStG)')),
                ('default_due_days', models.PositiveIntegerField(default=14)),
                ('invoice_number_prefix', models.CharField(default='RE', max_length=10)),
                ('storno_number_prefix', models.CharField(default='ST', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Firmeneinstellungen',
            },
        ),
    ]
