# Generated by Django 6.1.1 on 2026-09-07 08:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Rechnung'), ('STORNO', 'Stornorechnung')], default='INVOICE', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('ISSUED', 'Offen'), ('PAID', 'Bezahlt'), ('OVERDUE', 'Überfällig'), ('CANCELLED', 'Storniert')], default='DRAFT', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/')),
                ('xml_content', models.TextField(blank=True)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancels_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storno_documents', to='invoices.invoice')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATED', 'Erstellt'), ('FINALIZED', 'Finalisiert'), ('EXPORTED_PDF', 'PDF exportiert'), ('MARKED_PAID', 'Als bezahlt markiert'), ('CANCELLED', 'Storniert')], max_length=20)),
                ('actor', models.CharField(default='system', max_length=255)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Revisionsprotokolleintrag',
                'verbose_name_plural': 'Revisionsprotokoll',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NumberingCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('series', 'year')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_index', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_label', models.CharField(default='Std.', max_length=30)),
                ('unit_code', models.CharField(blank=True, max_length=3)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_scenario', models.CharField(choices=[('STANDARD', 'Standard (19%)'), ('REDUCED', 'Ermäßigt (7%)'), ('SMALL_BUSINESS', 'Kleinunternehmerregelung (§ 19 UStG)'), ('REVERSE_CHARGE', 'Bauleistung (§ 13b UStG, Reverse Charge)')], default='STANDARD', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('tax_category_code', models.CharField(blank=True, max_length=2)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Rechnungsposition',
                'verbose_name_plural': 'Rechnungspositionen',
                'ordering': ['position_index'],
                'unique_together': {('invoice', 'position_index')},
            },
        ),
    ]
