# Generated by Django 6.1.1 on 2026-09-07 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Erstellt'), ('FINALIZED', 'Finalisiert'), ('EXPORTED_PDF', 'PDF exportiert'), ('MARKED_PAID', 'Als bezahlt markiert'), ('REMINDER_SENT', 'Zahlungserinnerung erstellt'), ('CANCELLED', 'Storniert'), ('MARKED_OVERDUE', 'Als überfällig markiert')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Zahlungserinnerung',
                'verbose_name_plural': 'Zahlungserinnerungen',
                'ordering': ['created_at'],
            },
        ),
    ]
