# Generated by Django 6.1.1 on 2026-09-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_paid_date_alter_auditlogentry_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='signature',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
