# Generated by Django 6.1.1 on 2026-09-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_backfill_auditlogentry_signature'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numberingcounter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='numberingcounter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='numberingcounter',
            unique_together={('tenant', 'series', 'year')},
        ),
    ]
